#!/bin/bash
set -e

# Environment variables (set by docker-compose)
DOMAIN=${DOMAIN:-"example.com"}
MAILSERVER_HOSTNAME=${MAILSERVER_HOSTNAME:-"mx.${DOMAIN}"}
DB_HOST=${DB_HOST:-"host.docker.internal"}
DB_NAME=${DB_NAME:-"hibana"}
DB_USER=${DB_USER:-"hibana"}
DB_PASSWORD=${DB_PASSWORD:-""}

echo "=== Hibana Mail Server Starting ==="
echo "Domain: ${DOMAIN}"
echo "Hostname: ${MAILSERVER_HOSTNAME}"
echo "Database: ${DB_NAME}@${DB_HOST}"

# Set hostname (write to /etc/hostname, skip hostname command in containers)
echo "${MAILSERVER_HOSTNAME}" > /etc/hostname
# Note: 'hostname' command requires CAP_SYS_ADMIN in Docker, so we skip it
# Services will read from /etc/hostname instead

# Create mail directory for this domain
mkdir -p "/var/mail/vhosts/${DOMAIN}"
chown -R vmail:vmail "/var/mail/vhosts/${DOMAIN}"

# Generate self-signed certificate if not provided
if [ ! -f "/etc/ssl/certs/mail.crt" ]; then
    echo "Generating self-signed SSL certificate..."
    openssl req -x509 -nodes \
        -days 365 \
        -newkey rsa:2048 \
        -keyout /etc/ssl/private/mail.key \
        -out /etc/ssl/certs/mail.crt \
        -subj "/C=US/ST=State/L=City/O=Hibana/CN=${MAILSERVER_HOSTNAME}"
    chmod 600 /etc/ssl/private/mail.key
fi

# Generate DKIM keys if not exists
DKIM_DOMAIN_DIR="/etc/opendkim/keys/${DOMAIN}"
if [ ! -f "${DKIM_DOMAIN_DIR}/default.private" ]; then
    echo "Generating DKIM keys for ${DOMAIN}..."
    mkdir -p "${DKIM_DOMAIN_DIR}"
    opendkim-genkey -b 2048 -d "${DOMAIN}" -D "${DKIM_DOMAIN_DIR}" -s default -v
    chown -R opendkim:opendkim "${DKIM_DOMAIN_DIR}"
    chmod 600 "${DKIM_DOMAIN_DIR}/default.private"
    echo "DKIM public key:"
    cat "${DKIM_DOMAIN_DIR}/default.txt"
fi

# Configure OpenDKIM
cat > /etc/opendkim.conf <<EOF
AutoRestart             Yes
AutoRestartRate         10/1h
UMask                   002
Syslog                  yes
SyslogSuccess           Yes
LogWhy                  Yes
Canonicalization        relaxed/simple
ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts
KeyTable                refile:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
Mode                    sv
PidFile                 /run/opendkim/opendkim.pid
SignatureAlgorithm      rsa-sha256
UserID                  opendkim:opendkim
UMask                   002
Socket                  local:/run/opendkim/opendkim.sock
EOF

# Configure OpenDKIM tables
cat > /etc/opendkim/TrustedHosts <<EOF
127.0.0.1
localhost
${DOMAIN}
*.${DOMAIN}
EOF

cat > /etc/opendkim/KeyTable <<EOF
default._domainkey.${DOMAIN} ${DOMAIN}:default:${DKIM_DOMAIN_DIR}/default.private
EOF

cat > /etc/opendkim/SigningTable <<EOF
*@${DOMAIN} default._domainkey.${DOMAIN}
EOF

chown -R opendkim:opendkim /etc/opendkim

# Add postfix to opendkim group for milter socket access
usermod -a -G opendkim postfix

# Ensure the opendkim socket directory has correct permissions
mkdir -p /run/opendkim
chown opendkim:opendkim /run/opendkim
chmod 755 /run/opendkim

# Configure Postfix main.cf
cat > /etc/postfix/main.cf <<EOF
# Postfix Main Configuration - Generated by Hibana Mail Container

smtpd_banner = \$myhostname ESMTP
biff = no
append_dot_mydomain = no
readme_directory = no
compatibility_level = 3.6

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/mail.crt
smtpd_tls_key_file=/etc/ssl/private/mail.key
smtpd_tls_security_level=may
smtp_tls_CApath=/etc/ssl/certs
smtp_tls_security_level=may
smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache

# Basic configuration
myhostname = ${MAILSERVER_HOSTNAME}
mydomain = ${DOMAIN}
myorigin = \$mydomain
mydestination = \$myhostname, localhost.\$mydomain, localhost
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.16.0.0/12 10.0.0.0/8
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

# Virtual domains and users
virtual_mailbox_domains = ${DOMAIN}
virtual_mailbox_base = /var/mail/vhosts
virtual_mailbox_maps = pgsql:/etc/postfix/pgsql-virtual-mailbox-maps.cf
virtual_minimum_uid = 100
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000
virtual_alias_maps = pgsql:/etc/postfix/pgsql-virtual-alias-maps.cf

# SMTP Authentication
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
smtpd_sasl_security_options = noanonymous
smtpd_sasl_local_domain = \$mydomain
broken_sasl_auth_clients = yes

# SMTP Restrictions
smtpd_recipient_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unauth_destination

smtpd_helo_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_invalid_helo_hostname,
    reject_non_fqdn_helo_hostname

smtpd_sender_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_non_fqdn_sender,
    reject_unknown_sender_domain

# DKIM
milter_default_action = accept
milter_protocol = 6
smtpd_milters = local:/run/opendkim/opendkim.sock
non_smtpd_milters = local:/run/opendkim/opendkim.sock

# Other settings
home_mailbox = Maildir/
EOF

# Configure Postfix master.cf
cat > /etc/postfix/master.cf <<'EOF'
smtp      inet  n       -       n       -       -       smtpd
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=may
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination
smtps     inet  n       -       n       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination
pickup    unix  n       -       y       60      1       pickup
cleanup   unix  n       -       y       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       y       1000?   1       tlsmgr
rewrite   unix  -       -       y       -       -       trivial-rewrite
bounce    unix  -       -       y       -       0       bounce
defer     unix  -       -       y       -       0       bounce
trace     unix  -       -       y       -       0       bounce
verify    unix  -       -       y       -       1       verify
flush     unix  n       -       y       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       y       -       -       smtp
relay     unix  -       -       y       -       -       smtp
showq     unix  n       -       y       -       -       showq
error     unix  -       -       y       -       -       error
retry     unix  -       -       y       -       -       error
discard   unix  -       -       y       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       y       -       1       anvil
scache    unix  -       -       y       -       1       scache
EOF

# Configure Postfix PostgreSQL maps
cat > /etc/postfix/pgsql-virtual-mailbox-maps.cf <<EOF
hosts = ${DB_HOST}
user = ${DB_USER}
password = ${DB_PASSWORD}
dbname = ${DB_NAME}
query = SELECT 1 FROM email_accounts ea JOIN domains d ON ea.domain_id = d.id WHERE ea.username = '%u' AND d.name = '%d'
EOF

cat > /etc/postfix/pgsql-virtual-alias-maps.cf <<EOF
hosts = ${DB_HOST}
user = ${DB_USER}
password = ${DB_PASSWORD}
dbname = ${DB_NAME}
query = SELECT destination_addresses FROM email_aliases ea JOIN domains d ON ea.domain_id = d.id WHERE ea.source_address = '%u' AND d.name = '%d' AND ea.is_active = true
EOF

chmod 640 /etc/postfix/pgsql-*.cf
chown root:postfix /etc/postfix/pgsql-*.cf

# Copy hosts file to Postfix chroot (needed for pgsql lookups)
mkdir -p /var/spool/postfix/etc
cp /etc/hosts /var/spool/postfix/etc/hosts
cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf
cp /etc/nsswitch.conf /var/spool/postfix/etc/nsswitch.conf

# Configure Dovecot
cat > /etc/dovecot/dovecot.conf <<EOF
# Dovecot Configuration - Generated by Hibana Mail Container

protocols = imap pop3 lmtp
listen = *, ::

# SSL/TLS
ssl = yes
ssl_cert = </etc/ssl/certs/mail.crt
ssl_key = </etc/ssl/private/mail.key
ssl_min_protocol = TLSv1.2

# Allow plaintext authentication (for internal network)
disable_plaintext_auth = no

# Mail location
mail_location = maildir:/var/mail/vhosts/%d/%n
mail_privileged_group = vmail

# Authentication
auth_mechanisms = plain login

# SQL Authentication
passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
}

# IMAP configuration
protocol imap {
  mail_plugins = \$mail_plugins
}

# POP3 configuration
protocol pop3 {
  mail_plugins = \$mail_plugins
}

# LMTP configuration
protocol lmtp {
  postmaster_address = postmaster@${DOMAIN}
  mail_plugins = \$mail_plugins sieve
}

# Postfix SASL auth
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

# Namespace
namespace inbox {
  inbox = yes
}

# Sieve filtering
plugin {
  sieve = file:~/sieve;active=~/.dovecot.sieve
  sieve_default = /var/lib/dovecot/sieve/default.sieve
  sieve_default_name = main
}
EOF

# Configure Dovecot SQL
cat > /etc/dovecot/dovecot-sql.conf.ext <<EOF
driver = pgsql
connect = host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD}
default_pass_scheme = BLF-CRYPT
password_query = SELECT ea.username AS user, ea.password_hash AS password FROM email_accounts ea JOIN domains d ON ea.domain_id = d.id WHERE ea.username = '%n' AND d.name = '%d'
EOF

chmod 600 /etc/dovecot/dovecot-sql.conf.ext

# Configure SpamAssassin
cat > /etc/spamassassin/local.cf <<EOF
rewrite_header Subject [SPAM]
report_safe 0
required_score 5.0
use_bayes 1
bayes_auto_learn 1
EOF

# Fix postfix chroot
postfix set-permissions || true

# Create rsyslog configuration for mail logging
cat > /etc/rsyslog.d/mail.conf <<EOF
mail.*  /var/log/mail/mail.log
EOF

echo "=== Configuration complete, starting services ==="

exec "$@"
