---
- name: Restart Postfix
  systemd:
    name: postfix
    state: restarted

- name: Restart Dovecot
  systemd:
    name: dovecot
    state: restarted

- name: Rebuild Postfix maps
  command: postmap /etc/postfix/vmailbox
