[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/rsyslog.log
stderr_logfile=/var/log/supervisor/rsyslog_err.log

[program:opendkim]
command=/usr/sbin/opendkim -f
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/opendkim.log
stderr_logfile=/var/log/supervisor/opendkim_err.log

[program:spamassassin]
command=/usr/sbin/spamd --create-prefs --max-children 5 --helper-home-dir -u debian-spamd
autostart=true
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/spamassassin.log
stderr_logfile=/var/log/supervisor/spamassassin_err.log

[program:postfix]
command=/usr/sbin/postfix start-fg
autostart=true
autorestart=true
priority=40
stdout_logfile=/var/log/supervisor/postfix.log
stderr_logfile=/var/log/supervisor/postfix_err.log

[program:dovecot]
command=/usr/sbin/dovecot -F
autostart=true
autorestart=true
priority=50
stdout_logfile=/var/log/supervisor/dovecot.log
stderr_logfile=/var/log/supervisor/dovecot_err.log
